-- Part 4: Class 12 Chemistry, Math, and Biology

-- ===========================
-- CLASS 12 CHEMISTRY CHAPTERS (PCM)
-- ===========================
DO $$
DECLARE
    chemistry_12_pcm_id UUID;
BEGIN
    SELECT id INTO chemistry_12_pcm_id FROM public.subjects WHERE name = 'Chemistry' AND class_level = 12 AND stream = 'pcm' LIMIT 1;
    
    INSERT INTO public.chapters (subject_id, name, chapter_number, summary, content) VALUES
    (chemistry_12_pcm_id, 'The Solid State', 1,
     'Classification of solids, crystal lattices, packing, and defects in solids.',
     E'Solid State chemistry deals with structure and properties of solids.\n\nClassification of Solids:\n\n1. Crystalline Solids:\n   - Definite geometric shape\n   - Sharp melting point\n   - Anisotropic properties\n   - Examples: NaCl, Diamond, Quartz\n\n2. Amorphous Solids:\n   - Irregular shape\n   - No sharp melting point\n   - Isotropic properties\n   - Examples: Glass, Rubber, Plastic\n\nTypes of Crystalline Solids:\n1. Molecular: H₂, I₂, CO₂\n2. Ionic: NaCl, CaF₂\n3. Metallic: Cu, Fe, Al\n4. Covalent/Network: Diamond, SiO₂\n\nCrystal Lattice:\n3D arrangement of constituent particles\n\nUnit Cell:\nSmallest repeating unit of crystal lattice\n\nTypes:\n1. Simple Cubic (SC)\n2. Body-Centered Cubic (BCC)\n3. Face-Centered Cubic (FCC)\n\nPacking Efficiency:\n- SC: 52.4%\n- BCC: 68%\n- FCC/HCP: 74%\n\nCoordination Number:\nNumber of nearest neighbors\n- SC: 6\n- BCC: 8\n- FCC: 12\n\nDefects in Solids:\n\n1. Point Defects:\n   - Vacancy defect\n   - Interstitial defect\n   - Impurity defect\n\n2. Stoichiometric Defects:\n   - Schottky defect (ionic solids)\n   - Frenkel defect (ionic solids)\n\n3. Non-stoichiometric Defects:\n   - Metal excess\n   - Metal deficiency\n\nElectrical Properties:\n- Conductors: σ > 10⁴ S/m\n- Insulators: σ < 10⁻¹⁰ S/m\n- Semiconductors: Intermediate\n\nMagnetic Properties:\n- Diamagnetic\n- Paramagnetic\n- Ferromagnetic'
    ),
    (chemistry_12_pcm_id, 'Solutions', 2,
     'Types of solutions, concentration, solubility, colligative properties, and ideal solutions.',
     E'Solutions are homogeneous mixtures of two or more substances.\n\nComponents:\n- Solute: Present in smaller amount\n- Solvent: Present in larger amount\n\nTypes of Solutions:\nBased on physical state:\n- Solid in liquid: Sugar in water\n- Liquid in liquid: Alcohol in water\n- Gas in liquid: CO₂ in water\n\nConcentration:\n\n1. Mass Percentage:\n   (Mass of solute/Mass of solution) × 100\n\n2. Volume Percentage:\n   (Volume of solute/Volume of solution) × 100\n\n3. Molarity (M):\n   Moles of solute/Liters of solution\n\n4. Molality (m):\n   Moles of solute/Kg of solvent\n\n5. Mole Fraction (x):\n   Moles of component/Total moles\n\nSolubility:\nMaximum amount that dissolves at given temperature\n\nFactors Affecting Solubility:\n1. Nature of solute and solvent\n2. Temperature\n3. Pressure (for gases)\n\nHenry''s Law:\nFor gases in liquids:\np = KH × x\n\nRaoult''s Law:\nFor ideal solutions:\nP = P₁⁰x₁ + P₂⁰x₂\n\nColligative Properties:\nDepend only on number of particles, not nature\n\n1. Relative Lowering of Vapor Pressure:\n   (P₁⁰ - P₁)/P₁⁰ = x₂\n\n2. Elevation in Boiling Point:\n   ΔTb = Kb × m\n   Kb = ebullioscopic constant\n\n3. Depression in Freezing Point:\n   ΔTf = Kf × m\n   Kf = cryoscopic constant\n\n4. Osmotic Pressure:\n   π = CRT\n   Van''t Hoff equation\n\nAbnormal Molecular Mass:\nDue to association or dissociation\nVan''t Hoff factor: i\n\nIdeal Solutions:\n- Obey Raoult''s law\n- ΔHmix = 0\n- ΔVmix = 0'
    ),
    (chemistry_12_pcm_id, 'Electrochemistry', 3,
     'Electrochemical cells, electrode potential, Nernst equation, and electrolysis.',
     E'Electrochemistry studies interconversion of chemical and electrical energy.\n\nElectrochemical Cells:\n\n1. Galvanic/Voltaic Cell:\n   - Converts chemical energy to electrical\n   - Spontaneous reaction\n   - Example: Daniell cell\n\n2. Electrolytic Cell:\n   - Converts electrical to chemical energy\n   - Non-spontaneous reaction\n   - Example: Electrolysis of water\n\nCell Representation:\nAnode || Cathode\nZn | Zn²⁺ || Cu²⁺ | Cu\n\nElectrode Potential:\nTendency to lose or gain electrons\n\nStandard Electrode Potential (E⁰):\nMeasured at 298K, 1M, 1 atm\n\nStandard Hydrogen Electrode (SHE):\nReference electrode, E⁰ = 0V\n\nCell Potential:\nE⁰cell = E⁰cathode - E⁰anode\n\nNernst Equation:\nE = E⁰ - (RT/nF) ln Q\nAt 298K:\nE = E⁰ - (0.059/n) log Q\n\nRelation with Gibbs Energy:\nΔG⁰ = -nFE⁰\n\nConductance:\nG = 1/R\nUnit: Siemens (S)\n\nMolar Conductivity:\nΛm = κ × 1000/M\n\nKohlrausch''s Law:\nΛm⁰ = λ⁺⁰ + λ⁻⁰\nIonic conductivities are additive\n\nElectrolysis:\nDecomposition by electric current\n\nFaraday''s Laws:\n1. m ∝ Q\n2. m ∝ E (equivalent weight)\n\nApplications:\n- Electroplating\n- Electrorefining\n- Production of metals (Al, Na)\n- Batteries: Primary (dry cell), Secondary (lead storage)'
    ),
    (chemistry_12_pcm_id, 'Chemical Kinetics', 4,
     'Rate of reaction, factors affecting rate, order, molecularity, and Arrhenius equation.',
     E'Chemical Kinetics studies the rate and mechanism of chemical reactions.\n\nRate of Reaction:\nChange in concentration per unit time\nRate = -d[R]/dt = +d[P]/dt\n\nFactors Affecting Rate:\n1. Concentration: Rate ∝ [Reactant]\n2. Temperature: Rate increases with T\n3. Catalyst: Increases rate\n4. Surface Area: More area, faster rate\n5. Nature of reactants\n\nRate Law:\nRate = k[A]ˣ[B]ʸ\nWhere k = rate constant\n\nOrder of Reaction:\nSum of powers in rate law (x + y)\n\nTypes:\n1. Zero Order:\n   Rate = k\n   [A] = [A]₀ - kt\n   t₁/₂ = [A]₀/2k\n\n2. First Order:\n   Rate = k[A]\n   ln[A] = ln[A]₀ - kt\n   t₁/₂ = 0.693/k\n\n3. Second Order:\n   Rate = k[A]²\n   1/[A] = 1/[A]₀ + kt\n\nMolecularity:\nNumber of molecules in elementary step\nAlways whole number (1, 2, 3)\n\nDifference:\n- Order: Experimental, can be fraction\n- Molecularity: Theoretical, whole number\n\nTemperature Dependence:\n\nArrhenius Equation:\nk = Ae⁻Eₐ/RT\n\nWhere:\nA = pre-exponential factor\nEₐ = activation energy\n\nLogarithmic form:\nlog k = log A - Eₐ/2.303RT\n\nCollision Theory:\nFor reaction to occur:\n1. Molecules must collide\n2. Proper orientation\n3. Energy ≥ Eₐ\n\nCatalysis:\n- Positive: Increases rate (Eₐ decreases)\n- Negative: Decreases rate\n- Homogeneous: Same phase\n- Heterogeneous: Different phase\n- Enzymes: Biological catalysts'
    );
END $$;

-- ===========================
-- CLASS 12 CHEMISTRY CHAPTERS (PCB) - Same as PCM
-- ===========================
DO $$
DECLARE
    chemistry_12_pcb_id UUID;
BEGIN
    SELECT id INTO chemistry_12_pcb_id FROM public.subjects WHERE name = 'Chemistry' AND class_level = 12 AND stream = 'pcb' LIMIT 1;
    
    INSERT INTO public.chapters (subject_id, name, chapter_number, summary, content) VALUES
    (chemistry_12_pcb_id, 'The Solid State', 1,
     'Classification of solids, crystal lattices, packing, and defects in solids.',
     E'Solid State chemistry deals with structure and properties of solids.\n\nClassification of Solids:\n\n1. Crystalline Solids:\n   - Definite geometric shape\n   - Sharp melting point\n   - Anisotropic properties\n   - Examples: NaCl, Diamond, Quartz\n\n2. Amorphous Solids:\n   - Irregular shape\n   - No sharp melting point\n   - Isotropic properties\n   - Examples: Glass, Rubber, Plastic\n\nTypes of Crystalline Solids:\n1. Molecular: H₂, I₂, CO₂\n2. Ionic: NaCl, CaF₂\n3. Metallic: Cu, Fe, Al\n4. Covalent/Network: Diamond, SiO₂\n\nCrystal Lattice:\n3D arrangement of constituent particles\n\nUnit Cell:\nSmallest repeating unit of crystal lattice\n\nTypes:\n1. Simple Cubic (SC)\n2. Body-Centered Cubic (BCC)\n3. Face-Centered Cubic (FCC)\n\nPacking Efficiency:\n- SC: 52.4%\n- BCC: 68%\n- FCC/HCP: 74%\n\nCoordination Number:\nNumber of nearest neighbors\n- SC: 6\n- BCC: 8\n- FCC: 12\n\nDefects in Solids:\n\n1. Point Defects:\n   - Vacancy defect\n   - Interstitial defect\n   - Impurity defect\n\n2. Stoichiometric Defects:\n   - Schottky defect (ionic solids)\n   - Frenkel defect (ionic solids)\n\n3. Non-stoichiometric Defects:\n   - Metal excess\n   - Metal deficiency\n\nElectrical Properties:\n- Conductors: σ > 10⁴ S/m\n- Insulators: σ < 10⁻¹⁰ S/m\n- Semiconductors: Intermediate\n\nMagnetic Properties:\n- Diamagnetic\n- Paramagnetic\n- Ferromagnetic'
    ),
    (chemistry_12_pcb_id, 'Solutions', 2,
     'Types of solutions, concentration, solubility, colligative properties, and ideal solutions.',
     E'Solutions are homogeneous mixtures of two or more substances.\n\nComponents:\n- Solute: Present in smaller amount\n- Solvent: Present in larger amount\n\nTypes of Solutions:\nBased on physical state:\n- Solid in liquid: Sugar in water\n- Liquid in liquid: Alcohol in water\n- Gas in liquid: CO₂ in water\n\nConcentration:\n\n1. Mass Percentage:\n   (Mass of solute/Mass of solution) × 100\n\n2. Volume Percentage:\n   (Volume of solute/Volume of solution) × 100\n\n3. Molarity (M):\n   Moles of solute/Liters of solution\n\n4. Molality (m):\n   Moles of solute/Kg of solvent\n\n5. Mole Fraction (x):\n   Moles of component/Total moles\n\nSolubility:\nMaximum amount that dissolves at given temperature\n\nFactors Affecting Solubility:\n1. Nature of solute and solvent\n2. Temperature\n3. Pressure (for gases)\n\nHenry''s Law:\nFor gases in liquids:\np = KH × x\n\nRaoult''s Law:\nFor ideal solutions:\nP = P₁⁰x₁ + P₂⁰x₂\n\nColligative Properties:\nDepend only on number of particles, not nature\n\n1. Relative Lowering of Vapor Pressure:\n   (P₁⁰ - P₁)/P₁⁰ = x₂\n\n2. Elevation in Boiling Point:\n   ΔTb = Kb × m\n   Kb = ebullioscopic constant\n\n3. Depression in Freezing Point:\n   ΔTf = Kf × m\n   Kf = cryoscopic constant\n\n4. Osmotic Pressure:\n   π = CRT\n   Van''t Hoff equation\n\nAbnormal Molecular Mass:\nDue to association or dissociation\nVan''t Hoff factor: i\n\nIdeal Solutions:\n- Obey Raoult''s law\n- ΔHmix = 0\n- ΔVmix = 0'
    ),
    (chemistry_12_pcb_id, 'Electrochemistry', 3,
     'Electrochemical cells, electrode potential, Nernst equation, and electrolysis.',
     E'Electrochemistry studies interconversion of chemical and electrical energy.\n\nElectrochemical Cells:\n\n1. Galvanic/Voltaic Cell:\n   - Converts chemical energy to electrical\n   - Spontaneous reaction\n   - Example: Daniell cell\n\n2. Electrolytic Cell:\n   - Converts electrical to chemical energy\n   - Non-spontaneous reaction\n   - Example: Electrolysis of water\n\nCell Representation:\nAnode || Cathode\nZn | Zn²⁺ || Cu²⁺ | Cu\n\nElectrode Potential:\nTendency to lose or gain electrons\n\nStandard Electrode Potential (E⁰):\nMeasured at 298K, 1M, 1 atm\n\nStandard Hydrogen Electrode (SHE):\nReference electrode, E⁰ = 0V\n\nCell Potential:\nE⁰cell = E⁰cathode - E⁰anode\n\nNernst Equation:\nE = E⁰ - (RT/nF) ln Q\nAt 298K:\nE = E⁰ - (0.059/n) log Q\n\nRelation with Gibbs Energy:\nΔG⁰ = -nFE⁰\n\nConductance:\nG = 1/R\nUnit: Siemens (S)\n\nMolar Conductivity:\nΛm = κ × 1000/M\n\nKohlrausch''s Law:\nΛm⁰ = λ⁺⁰ + λ⁻⁰\nIonic conductivities are additive\n\nElectrolysis:\nDecomposition by electric current\n\nFaraday''s Laws:\n1. m ∝ Q\n2. m ∝ E (equivalent weight)\n\nApplications:\n- Electroplating\n- Electrorefining\n- Production of metals (Al, Na)\n- Batteries: Primary (dry cell), Secondary (lead storage)'
    ),
    (chemistry_12_pcb_id, 'Chemical Kinetics', 4,
     'Rate of reaction, factors affecting rate, order, molecularity, and Arrhenius equation.',
     E'Chemical Kinetics studies the rate and mechanism of chemical reactions.\n\nRate of Reaction:\nChange in concentration per unit time\nRate = -d[R]/dt = +d[P]/dt\n\nFactors Affecting Rate:\n1. Concentration: Rate ∝ [Reactant]\n2. Temperature: Rate increases with T\n3. Catalyst: Increases rate\n4. Surface Area: More area, faster rate\n5. Nature of reactants\n\nRate Law:\nRate = k[A]ˣ[B]ʸ\nWhere k = rate constant\n\nOrder of Reaction:\nSum of powers in rate law (x + y)\n\nTypes:\n1. Zero Order:\n   Rate = k\n   [A] = [A]₀ - kt\n   t₁/₂ = [A]₀/2k\n\n2. First Order:\n   Rate = k[A]\n   ln[A] = ln[A]₀ - kt\n   t₁/₂ = 0.693/k\n\n3. Second Order:\n   Rate = k[A]²\n   1/[A] = 1/[A]₀ + kt\n\nMolecularity:\nNumber of molecules in elementary step\nAlways whole number (1, 2, 3)\n\nDifference:\n- Order: Experimental, can be fraction\n- Molecularity: Theoretical, whole number\n\nTemperature Dependence:\n\nArrhenius Equation:\nk = Ae⁻Eₐ/RT\n\nWhere:\nA = pre-exponential factor\nEₐ = activation energy\n\nLogarithmic form:\nlog k = log A - Eₐ/2.303RT\n\nCollision Theory:\nFor reaction to occur:\n1. Molecules must collide\n2. Proper orientation\n3. Energy ≥ Eₐ\n\nCatalysis:\n- Positive: Increases rate (Eₐ decreases)\n- Negative: Decreases rate\n- Homogeneous: Same phase\n- Heterogeneous: Different phase\n- Enzymes: Biological catalysts'
    );
END $$;
