-- Part 5: Class 12 Mathematics and Biology

-- ===========================
-- CLASS 12 MATHEMATICS CHAPTERS (PCM only)
-- ===========================
DO $$
DECLARE
    math_12_id UUID;
BEGIN
    SELECT id INTO math_12_id FROM public.subjects WHERE name = 'Mathematics' AND class_level = 12 AND stream = 'pcm' LIMIT 1;
    
    INSERT INTO public.chapters (subject_id, name, chapter_number, summary, content) VALUES
    (math_12_id, 'Relations and Functions', 1,
     'Types of relations, functions, inverse functions, and binary operations.',
     E'Advanced concepts of relations and functions build upon Class 11 foundations.\n\nTypes of Relations:\n\n1. Empty Relation:\n   R = ∅\n\n2. Universal Relation:\n   R = A × A\n\n3. Reflexive Relation:\n   (a, a) ∈ R for all a ∈ A\n\n4. Symmetric Relation:\n   If (a, b) ∈ R, then (b, a) ∈ R\n\n5. Transitive Relation:\n   If (a, b) ∈ R and (b, c) ∈ R, then (a, c) ∈ R\n\n6. Equivalence Relation:\n   Reflexive, Symmetric, and Transitive\n\nTypes of Functions:\n\n1. One-One (Injective):\n   f(x₁) = f(x₂) ⇒ x₁ = x₂\n\n2. Onto (Surjective):\n   Range = Codomain\n\n3. Bijective:\n   Both one-one and onto\n\nInverse Functions:\nIf f: A → B is bijective, then f⁻¹: B → A exists\n\nProperties:\n1. (f⁻¹)⁻¹ = f\n2. (fog)⁻¹ = g⁻¹of⁻¹\n\nBinary Operations:\nOperation * : A × A → A\n\nProperties:\n1. Commutative: a * b = b * a\n2. Associative: (a * b) * c = a * (b * c)\n3. Identity: a * e = e * a = a\n4. Inverse: a * a⁻¹ = e\n\nComposition of Functions:\n(fog)(x) = f(g(x))\n\nDomain of fog:\n{x : x ∈ domain of g, g(x) ∈ domain of f}\n\nInvertible Functions:\nFunction that has inverse\nCondition: Must be bijective'
    ),
    (math_12_id, 'Inverse Trigonometric Functions', 2,
     'Definitions, domains, ranges, and properties of inverse trigonometric functions.',
     E'Inverse trigonometric functions reverse the trigonometric ratios.\n\nNotation:\nsin⁻¹x, cos⁻¹x, tan⁻¹x, cot⁻¹x, sec⁻¹x, cosec⁻¹x\n\nDomains and Ranges:\n\n1. sin⁻¹x:\n   Domain: [-1, 1]\n   Range: [-π/2, π/2]\n\n2. cos⁻¹x:\n   Domain: [-1, 1]\n   Range: [0, π]\n\n3. tan⁻¹x:\n   Domain: R (all real numbers)\n   Range: (-π/2, π/2)\n\n4. cot⁻¹x:\n   Domain: R\n   Range: (0, π)\n\n5. sec⁻¹x:\n   Domain: (-∞, -1] ∪ [1, ∞)\n   Range: [0, π] - {π/2}\n\n6. cosec⁻¹x:\n   Domain: (-∞, -1] ∪ [1, ∞)\n   Range: [-π/2, π/2] - {0}\n\nProperties:\n\n1. sin⁻¹x + cos⁻¹x = π/2\n2. tan⁻¹x + cot⁻¹x = π/2\n3. sec⁻¹x + cosec⁻¹x = π/2\n\n4. sin⁻¹(-x) = -sin⁻¹x\n5. tan⁻¹(-x) = -tan⁻¹x\n6. cos⁻¹(-x) = π - cos⁻¹x\n\n7. tan⁻¹x + tan⁻¹y = tan⁻¹[(x+y)/(1-xy)]\n8. tan⁻¹x - tan⁻¹y = tan⁻¹[(x-y)/(1+xy)]\n\n9. 2tan⁻¹x = sin⁻¹(2x/(1+x²))\n              = cos⁻¹((1-x²)/(1+x²))\n              = tan⁻¹(2x/(1-x²))\n\nComposition:\nsin(sin⁻¹x) = x, if x ∈ [-1, 1]\nsin⁻¹(sin x) = x, if x ∈ [-π/2, π/2]'
    ),
    (math_12_id, 'Matrices', 3,
     'Types of matrices, operations, transpose, determinants, and inverse of matrices.',
     E'A matrix is a rectangular array of numbers arranged in rows and columns.\n\nNotation:\nA = [aᵢⱼ]ₘₓₙ\nOrder: m × n (m rows, n columns)\n\nTypes of Matrices:\n\n1. Row Matrix: 1 × n\n2. Column Matrix: m × 1\n3. Square Matrix: m = n\n4. Diagonal Matrix: aᵢⱼ = 0 for i ≠ j\n5. Scalar Matrix: Diagonal with equal elements\n6. Identity Matrix: I, diagonal elements = 1\n7. Zero Matrix: All elements = 0\n8. Upper Triangular: aᵢⱼ = 0 for i > j\n9. Lower Triangular: aᵢⱼ = 0 for i < j\n10. Symmetric: A = Aᵀ\n11. Skew-symmetric: A = -Aᵀ\n\nOperations:\n\n1. Addition/Subtraction:\n   Same order matrices\n   [aᵢⱼ] ± [bᵢⱼ] = [aᵢⱼ ± bᵢⱼ]\n\n2. Scalar Multiplication:\n   k[aᵢⱼ] = [kaᵢⱼ]\n\n3. Matrix Multiplication:\n   If A is m×n and B is n×p, then AB is m×p\n   (AB)ᵢₖ = Σ aᵢⱼbⱼₖ\n\nProperties:\n1. A + B = B + A (commutative)\n2. (A + B) + C = A + (B + C) (associative)\n3. AB ≠ BA (not commutative generally)\n4. (AB)C = A(BC) (associative)\n5. A(B + C) = AB + AC (distributive)\n\nTranspose:\n(Aᵀ)ᵢⱼ = Aⱼᵢ\nProperties:\n1. (Aᵀ)ᵀ = A\n2. (A + B)ᵀ = Aᵀ + Bᵀ\n3. (AB)ᵀ = BᵀAᵀ\n4. (kA)ᵀ = kAᵀ\n\nDeterminant (for square matrices):\n|A| or det(A)\n\nFor 2×2: |a b| = ad - bc\n         |c d|\n\nProperties:\n1. |Aᵀ| = |A|\n2. |AB| = |A||B|\n3. |kA| = kⁿ|A| (n = order)\n\nSingular Matrix: |A| = 0\nNon-singular: |A| ≠ 0\n\nAdjoint:\nadj(A) = [cofactor matrix]ᵀ\n\nInverse:\nA⁻¹ = adj(A)/|A|\nExists only if |A| ≠ 0\n\nProperties:\n1. AA⁻¹ = I\n2. (AB)⁻¹ = B⁻¹A⁻¹\n3. (Aᵀ)⁻¹ = (A⁻¹)ᵀ'
    ),
    (math_12_id, 'Determinants', 4,
     'Properties of determinants, minors, cofactors, and applications.',
     E'Determinant is a scalar value associated with every square matrix.\n\nDeterminant of Order 2:\n|a₁ b₁|\n|a₂ b₂| = a₁b₂ - a₂b₁\n\nDeterminant of Order 3:\n|a₁ b₁ c₁|\n|a₂ b₂ c₂| = a₁(b₂c₃ - b₃c₂) - b₁(a₂c₃ - a₃c₂) + c₁(a₂b₃ - a₃b₂)\n|a₃ b₃ c₃|\n\nMinor:\nMᵢⱼ = determinant after removing iᵗʰ row and jᵗʰ column\n\nCofactor:\nCᵢⱼ = (-1)ⁱ⁺ʲ Mᵢⱼ\n\nExpansion:\nAlong any row or column:\n|A| = Σ aᵢⱼCᵢⱼ\n\nProperties of Determinants:\n\n1. |Aᵀ| = |A|\n\n2. Row/Column Interchange:\n   Interchanging rows/columns changes sign\n\n3. Identical Rows/Columns:\n   If two rows/columns identical, |A| = 0\n\n4. Scalar Multiplication:\n   |kA| = kⁿ|A| (n = order)\n\n5. Row/Column Operations:\n   Adding multiple of one row to another doesn''t change determinant\n\n6. Triangular Matrix:\n   |A| = product of diagonal elements\n\n7. Product:\n   |AB| = |A||B|\n\n8. Zero Row/Column:\n   If any row/column is zero, |A| = 0\n\n9. Proportional Rows/Columns:\n   If proportional, |A| = 0\n\nArea of Triangle:\nVertices (x₁,y₁), (x₂,y₂), (x₃,y₃)\n\nArea = ½|x₁(y₂-y₃) + x₂(y₃-y₁) + x₃(y₁-y₂)|\n\nor using determinant:\n     |x₁ y₁ 1|\nΔ = ½|x₂ y₂ 1|\n     |x₃ y₃ 1|\n\nApplications:\n1. Finding area of triangle/polygon\n2. Collinearity of points\n3. Solving system of equations\n4. Finding inverse of matrix\n\nSingular vs Non-singular:\n- Singular: |A| = 0 (no inverse)\n- Non-singular: |A| ≠ 0 (inverse exists)'
    );
END $$;

-- ===========================
-- CLASS 12 BIOLOGY CHAPTERS (PCB only)
-- ===========================
DO $$
DECLARE
    biology_12_id UUID;
BEGIN
    SELECT id INTO biology_12_id FROM public.subjects WHERE name = 'Biology' AND class_level = 12 AND stream = 'pcb' LIMIT 1;
    
    INSERT INTO public.chapters (subject_id, name, chapter_number, summary, content) VALUES
    (biology_12_id, 'Reproduction in Organisms', 1,
     'Modes of reproduction, asexual and sexual reproduction in plants and animals.',
     E'Reproduction is the biological process by which new organisms are produced.\n\nImportance:\n- Continuation of species\n- Maintains population\n- Introduces variations\n\nModes of Reproduction:\n\n1. Asexual Reproduction:\n   Single parent, no gamete fusion\n   Offspring genetically identical (clones)\n\nTypes:\na) Binary Fission:\n   - Parent divides into 2 equal parts\n   - Examples: Amoeba, Bacteria\n\nb) Budding:\n   - New individual from outgrowth\n   - Examples: Yeast, Hydra\n\nc) Fragmentation:\n   - Body breaks into fragments\n   - Each develops into new organism\n   - Examples: Spirogyra, Planaria\n\nd) Regeneration:\n   - Lost body parts regrown\n   - Examples: Hydra, Planaria, Starfish\n\ne) Spore Formation:\n   - Spores germinate to form new organism\n   - Examples: Fungi, Ferns, Mosses\n\nf) Vegetative Propagation:\n   - New plants from vegetative parts\n   - Natural: Runner, Rhizome, Bulb, Tuber\n   - Artificial: Cutting, Layering, Grafting\n\n2. Sexual Reproduction:\n   Two parents involved\n   Fusion of gametes (fertilization)\n   Offspring show variations\n\nStages:\na) Pre-fertilization:\n   - Gametogenesis: Formation of gametes\n   - Gamete transfer\n\nb) Fertilization:\n   - Fusion of male and female gametes\n   - Zygote formation\n\nc) Post-fertilization:\n   - Zygote development\n   - Embryogenesis\n\nTypes of Gametes:\n- Isogametes: Similar in appearance\n- Anisogametes (Heterogametes): Different\n  * Male gamete: Small, motile\n  * Female gamete: Large, non-motile\n\nFertilization:\n- External: Outside body (fish, frogs)\n- Internal: Inside body (birds, mammals)\n\nSexuality in Organisms:\n- Bisexual: Both male and female organs\n- Unisexual: Either male or female organs'
    ),
    (biology_12_id, 'Sexual Reproduction in Flowering Plants', 2,
     'Structure of flower, pollination, fertilization, and seed formation.',
     E'Flowering plants (angiosperms) show advanced sexual reproduction.\n\nFlower Structure:\nReproductive organ of angiosperms\n\nParts:\n1. Calyx: Sepals (green, protective)\n2. Corolla: Petals (colorful, attract pollinators)\n3. Androecium: Male part\n   - Stamen = Filament + Anther\n   - Anther produces pollen grains\n4. Gynoecium: Female part\n   - Pistil = Stigma + Style + Ovary\n   - Ovary contains ovules\n\nMicrosporogenesis:\nFormation of pollen grains (microspores)\n- Occurs in anther\n- Pollen mother cell (PMC) undergoes meiosis\n- Forms 4 haploid pollen grains\n\nPollen Grain Structure:\n- Two-layered wall: Exine (outer), Intine (inner)\n- Two cells: Vegetative cell, Generative cell\n\nMegasporogenesis:\nFormation of embryo sac (megaspore)\n- Occurs in ovule\n- Megaspore mother cell (MMC) undergoes meiosis\n- Forms 4 megaspores (3 degenerate, 1 survives)\n- Develops into 7-celled, 8-nucleate embryo sac\n\nPollination:\nTransfer of pollen from anther to stigma\n\nTypes:\n1. Self-pollination: Same flower/plant\n2. Cross-pollination: Different plants\n\nAgents:\n- Wind (anemophily)\n- Water (hydrophily)\n- Insects (entomophily)\n- Animals\n\nOutbreeding Devices:\nPrevent self-pollination\n- Dicliny: Unisexual flowers\n- Dichogamy: Different maturation times\n- Self-incompatibility\n- Heterostyly\n\nDouble Fertilization:\nUnique to angiosperms\n\nProcess:\n1. Pollen tube enters embryo sac\n2. Releases 2 male gametes\n3. Syngamy: One male gamete + egg → Zygote (2n)\n4. Triple fusion: One male gamete + 2 polar nuclei → PEN (3n)\n\nPost-fertilization:\n- Zygote → Embryo\n- PEN → Endosperm (nutritive tissue)\n- Ovule → Seed\n- Ovary → Fruit\n\nSeed Structure:\n- Seed coat (from integuments)\n- Embryo (from zygote)\n- Endosperm (from PEN)\n\nFruit:\nRipened ovary\nProtects seeds and aids dispersal\n\nTypes:\n- True fruit: From ovary only\n- False fruit: Other floral parts involved'
    ),
    (biology_12_id, 'Human Reproduction', 3,
     'Male and female reproductive systems, menstrual cycle, fertilization, and pregnancy.',
     E'Human reproduction is sexual, producing genetically unique offspring.\n\nMale Reproductive System:\n\n1. Testes:\n   - Primary sex organs\n   - Produce sperms and testosterone\n   - Located in scrotum (2-3°C lower temperature)\n\n2. Accessory Ducts:\n   - Rete testis → Vasa efferentia → Epididymis → Vas deferens\n\n3. Accessory Glands:\n   - Seminal vesicles: Fructose (energy)\n   - Prostate: Alkaline fluid\n   - Bulbourethral glands: Lubricant\n\n4. External Genitalia:\n   - Penis: Copulatory organ\n\nSpermatogenesis:\nFormation of sperms in seminiferous tubules\n- Starts at puberty\n- Continuous process\n- Spermatogonium → Primary spermatocyte → Secondary spermatocyte → Spermatids → Sperms\n- Regulated by hormones: GnRH, LH, FSH, Testosterone\n\nFemale Reproductive System:\n\n1. Ovaries:\n   - Primary sex organs\n   - Produce ova and hormones (estrogen, progesterone)\n\n2. Accessory Ducts:\n   - Fallopian tubes (oviducts): Site of fertilization\n   - Uterus: Implantation and fetal development\n   - Vagina: Copulatory canal\n\n3. External Genitalia:\n   - Mons pubis, Labia majora, Labia minora, Clitoris\n\nOogenesis:\nFormation of ova in ovaries\n- Starts in fetal life, completes after fertilization\n- Oogonium → Primary oocyte → Secondary oocyte → Ovum\n- Only one functional ovum per cycle\n\nMenstrual Cycle:\n28-day cycle (average)\n\nPhases:\n1. Menstrual Phase (1-5 days):\n   - Breakdown of endometrium\n   - Menstrual flow\n\n2. Follicular Phase (6-13 days):\n   - Follicle development\n   - Endometrium regeneration\n   - FSH and LH secretion\n\n3. Ovulatory Phase (14th day):\n   - LH surge\n   - Release of ovum\n\n4. Luteal Phase (15-28 days):\n   - Corpus luteum forms\n   - Progesterone secretion\n   - Endometrium thickens\n\nFertilization:\n- Occurs in fallopian tube (ampullary region)\n- Fusion of sperm and ovum\n- Forms diploid zygote\n\nImplantation:\n- Blastocyst attaches to uterine wall\n- Occurs 7 days after fertilization\n\nPregnancy:\nAverage duration: 280 days (9 months)\n\nMajor Events:\n- Formation of placenta\n- Embryonic development\n- Fetal growth\n- Parturition (childbirth)\n\nHormones:\n- hCG: Maintains corpus luteum\n- Estrogen and Progesterone: Maintain pregnancy\n- Oxytocin: Labor contractions\n- Prolactin: Milk production'
    ),
    (biology_12_id, 'Reproductive Health', 4,
     'Reproductive health issues, population control, STDs, and infertility.',
     E'Reproductive health is total well-being in all aspects of reproduction.\n\nImportance:\n- Healthy society\n- Population control\n- Prevention of diseases\n\nReproductive Health Problems:\n\n1. Population Explosion:\n   - Rapid population growth\n   - Strain on resources\n\nSolution: Family Planning\n\n2. Sexually Transmitted Diseases (STDs):\n   - Gonorrhea, Syphilis (bacterial)\n   - AIDS, Hepatitis B (viral)\n   - Trichomoniasis (protozoan)\n\nPrevention:\n- Safe sex practices\n- Use of contraceptives (condoms)\n- Awareness and education\n\n3. Infertility:\n   Inability to produce children\n\nCauses:\n- Physical/hormonal problems\n- Low sperm count\n- Ovulation disorders\n\nAssisted Reproductive Technologies (ART):\na) IVF (In Vitro Fertilization):\n   - Test tube baby\n   - Fertilization outside body\n\nb) ZIFT (Zygote Intrafallopian Transfer):\n   - Zygote transferred to fallopian tube\n\nc) GIFT (Gamete Intrafallopian Transfer):\n   - Gametes transferred to fallopian tube\n\nd) ICSI (Intracytoplasmic Sperm Injection):\n   - Direct sperm injection into ovum\n\ne) AI (Artificial Insemination):\n   - Semen collected and introduced artificially\n\nContraception:\nMethods to prevent pregnancy\n\nNatural Methods:\n1. Periodic Abstinence (Rhythm method)\n2. Coitus Interruptus (Withdrawal)\n3. Lactational Amenorrhea\n\nBarrier Methods:\n1. Condoms (male and female)\n2. Diaphragm\n3. Cervical caps\n4. Spermicidal creams/jellies\n\nIntra Uterine Devices (IUDs):\n1. Copper-T\n2. Lippes loop\n\nHormonal Methods:\n1. Oral pills (combined/mini pills)\n2. Injectable contraceptives\n3. Implants\n4. Emergency contraceptives (morning-after pill)\n\nPermanent Methods:\n1. Tubectomy (females): Fallopian tubes ligated\n2. Vasectomy (males): Vas deferens cut and tied\n\nMedical Termination of Pregnancy (MTP):\n- Legal abortion\n- Safe and regulated\n- Used when pregnancy risk to mother\n\nAmniocentesis:\n- Prenatal diagnostic technique\n- Detects genetic disorders\n- Misused for sex determination (illegal)\n\nSex Determination:\n- Illegal in India (PNDT Act)\n- Leads to female foeticide'
    );
END $$;
